import { z } from 'zod';

export const BloomsBucketSchema = z
  .object({
    remember: z.number().min(0).max(1),
    understand: z.number().min(0).max(1),
    apply: z.number().min(0).max(1),
    analyze: z.number().min(0).max(1),
    evaluate: z.number().min(0).max(1),
    create: z.number().min(0).max(1),
  })
  .strict();

export const CoverageSchema = z
  .object({
    covered: z.array(z.string()).max(50),
    missing: z.array(z.string()).max(50),
    coverageRatio: z.number().min(0).max(1),
  })
  .strict();

export const QualityReportSchema = z
  .object({
    score: z.number().min(0).max(1),
    blooms: BloomsBucketSchema,
    coverage: CoverageSchema,
    suggestions: z.string().max(4000),
  })
  .strict();

export type QualityReportData = z.infer<typeof QualityReportSchema>;
export type BloomsBucket = z.infer<typeof BloomsBucketSchema>;
export type Coverage = z.infer<typeof CoverageSchema>;

// =====================================================================
// Handout draft (M11.1) — full handout generated by the LLM.
// =====================================================================

const EvaluativeComponentSchema = z
  .object({
    name: z.string().min(1).max(120),
    weightage: z.number().min(0).max(100),
    schedule: z.string().max(200).optional().default(''),
    nature: z.string().max(60).optional().default(''),
  })
  .strict();

export const HandoutDraftSchema = z
  .object({
    partA: z
      .object({
        courseDescription: z.string().min(1).max(4000),
        learningOutcomes: z.array(z.string().min(1).max(500)).min(1).max(12),
        pedagogy: z.string().min(1).max(2000),
        textbooks: z.array(z.string().min(1).max(300)).max(10).default([]),
        referenceBooks: z.array(z.string().min(1).max(300)).max(10).default([]),
      })
      .strict(),
    partB: z
      .object({
        lecturePlan: z
          .array(
            z
              .object({
                module: z.string().min(1).max(200),
                topics: z.array(z.string().min(1).max(300)).min(1).max(12),
                hours: z.number().min(0).max(40).default(0),
              })
              .strict(),
          )
          .min(1)
          .max(20),
        selfStudy: z.array(z.string().min(1).max(300)).max(20).default([]),
      })
      .strict(),
    evaluative: z
      .object({
        components: z.array(EvaluativeComponentSchema).min(1).max(10),
        notes: z.string().max(1000).optional().default(''),
      })
      .strict(),
  })
  .strict();

export type HandoutDraftData = z.infer<typeof HandoutDraftSchema>;
